app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth'], function () {

    Route::get('/home', 'HomeController@index');

    Route::resource('/customers', 'CustomersController');

    Route::resource('/visits', 'VisitsController');

});
Route::auth();

app/Models/Customers.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Customers extends Model
{
    protected $table = 'customers';
    protected $fillable = [
        'fantasy_name', 'company_name', 'cnpj', 'email', 'phone', 'city', 'district', 'state', 'address', 'zip_code', 'excluded'
    ];
}

app/Http/Controllers/Api/CustomersController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\CustomersRequest;
use App\Http\Controllers\Controller;

use App\Models\Customers;

class CustomersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = Customers::all(); 
        return response()->json($customers->toArray());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('customers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CustomersRequest $request)
    {
        if (Customers::create($request->all())) {
            return response()->json($request->all());
        }
        return response($content);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $customers = Customers::find($id);
        return response()->json($customers->toArray());
        //return view('customers.view', ['customers' => $customers]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customers = Customers::find($id);
        return view('customers.edit', ['customers' => $customers]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $customers = Customers::find($id);
        $customers->fill($request->all());
        $customers->save();

        return redirect('/customers');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Customers::destroy($id);
        return redirect('/customers');
    }
}

app/Http/Controllers/CustomersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\CustomersRequest;

use App\Models\Customers;

class CustomersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = Customers::paginate(5);
        return view('customers.index', ['customers' => $customers]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('customers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CustomersRequest $request)
    {
        if (Customers::create($request->all())) {
            return redirect('/customers');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $customers = Customers::find($id);
        return view('customers.view', ['customers' => $customers]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customers = Customers::find($id);
        return view('customers.edit', ['customers' => $customers]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CustomersRequest $request, $id)
    {
        $customers = Customers::find($id);
        $customers->fill($request->all());
        $customers->save();

        return redirect('/customers');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Customers::destroy($id);
        return redirect('/customers');
    }
}

resources/views/customers/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h2>Novo Cliente</h2>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-7">
                            {!!Form::open(['route'=>'customers.store', 'method'=>'POST'])!!}
                                @include('customers.form')
                                {!!Form::submit('Cadastrar', ['class' => "btn btn-lg btn-success"])!!}
                                <a href="{{ url()->previous() }}" class="btn btn-lg btn-danger">Back</a>
                            {!!Form::close()!!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/customers/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h2>Cliente: {{$customers->fantasy_name}}</h2>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-7">
                            {!!Form::model($customers, ['route'=> ['customers.update', $customers->id], 'method'=>'PUT'])!!}
                                @include('customers.form')
                                {!!Form::submit('Atualizar', ['class' => "btn btn-lg btn-success"])!!}
                                <a href="{{ url()->previous() }}" class="btn btn-lg btn-danger">Back</a>
                            {!!Form::close()!!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/customers/form.blade.php
<?php
use App\Helpers\StatesHelper;
?>

<div class="form-group {{ $errors->has('fantasy_name') ? ' has-error' : '' }}">
    {!!Form::label('fantasy_name', 'Nome Fantasia', [])!!}
    {!!Form::text('fantasy_name', null, ['class' => "form-control", 'alt'=>"Nome Fantasia"])!!}
    @if ($errors->has('fantasy_name'))
        <span class="help-block">
            <strong>{{ $errors->first('fantasy_name') }}</strong>
        </span>
    @endif

</div>
<div class="form-group {{ $errors->has('company_name') ? ' has-error' : '' }}">
    {!!Form::label('company_name', 'Razão Social', [])!!}
    {!!Form::text('company_name', null, ['class' => "form-control", 'alt'=>"Razão Social"])!!}
    @if ($errors->has('company_name'))
        <span class="help-block">
            <strong>{{ $errors->first('company_name') }}</strong>
        </span>
    @endif

</div>
<div class="form-group {{ $errors->has('cnpj') ? ' has-error' : '' }}">
    {!!Form::label('cnpj', null, [])!!}
    {!!Form::text('cnpj', null,['class' => "form-control", 'alt' => "CNPJ"])!!}
    @if ($errors->has('cnpj'))
        <span class="help-block">
            <strong>{{ $errors->first('cnpj') }}</strong>
        </span>
    @endif

</div>
<div class="form-group {{ $errors->has('email') ? ' has-error' : '' }}">
    {!!Form::label('email', null, [])!!} 
    {!!Form::email('email', null, ['class' => "form-control", 'alt'=>"E-mail"])!!}
    @if ($errors->has('email'))
        <span class="help-block">
            <strong>{{ $errors->first('email') }}</strong>
        </span>
    @endif

</div>

<div class="form-group {{ $errors->has('phone') ? ' has-error' : '' }}">
    {!!Form::label('phone', 'Telefone', [])!!}
    {!!Form::text('phone', null, ['class' => "form-control", 'alt' => "Telefone"])!!}
    @if ($errors->has('phone'))
        <span class="help-block">
            <strong>{{ $errors->first('phone') }}</strong>
        </span>
    @endif

</div>

<div class="form-group {{ $errors->has('city') ? ' has-error' : '' }}">
    {!!Form::label('city', 'Cidade', [])!!}
    {!!Form::select('city', array('01' => 'Niterói', '02' => 'São Gonçalo'), null, ['placeholder' => 'Selecione a cidade...', 'class' => "form-control"])!!}
    @if ($errors->has('city'))
        <span class="help-block">
            <strong>{{ $errors->first('city') }}</strong>
        </span>
    @endif

</div>

<div class="form-group {{ $errors->has('district') ? ' has-error' : '' }}">
    {!!Form::label('district', 'Bairro', [])!!}
    {!!Form::text('district', null, ['class' => "form-control", 'alt' => "Bairro"])!!}
    @if ($errors->has('district'))
        <span class="help-block">
            <strong>{{ $errors->first('district') }}</strong>
        </span>
    @endif

</div>

<div class="form-group {{ $errors->has('state') ? ' has-error' : '' }}">
    {!!Form::label('state', 'Estado', [])!!}
    {!!Form::select('state', StatesHelper::renderAll(), null, ['placeholder' => 'Selecione um estado...', 'class' => "form-control"])!!}
    @if ($errors->has('state'))
        <span class="help-block">
            <strong>{{ $errors->first('state') }}</strong>
        </span>
    @endif

</div>

<div class="form-group {{ $errors->has('address') ? ' has-error' : '' }}">
    {!!Form::label('address', 'Endereço', [])!!}
    {!!Form::text('address', null, ['class' => "form-control", 'alt' => "Endereço"])!!}
    @if ($errors->has('address'))
        <span class="help-block">
            <strong>{{ $errors->first('address') }}</strong>
        </span>
    @endif

</div>

<div class="form-group {{ $errors->has('zip_code') ? ' has-error' : '' }}">
    {!!Form::label('zip_code', 'CEP', [])!!}
    {!!Form::text('zip_code', null, ['class' => "form-control", 'alt' => "CEP"])!!}
    @if ($errors->has('zip_code'))
        <span class="help-block">
            <strong>{{ $errors->first('zip_code') }}</strong>
        </span>
    @endif

</div>

resources/views/customers/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-success">
                <div class="panel-heading">Clientes</div>

                <div class="panel-body">
                    <a href="{{ url('/customers/create') }}" class="btn btn-success">Novo Cliente</a>
                    <table class="table table-striped">
                    
                        <thead>
                            <tr>
                                <td> ID </td>
                                <td> Razao Social </td>
                                <td> Cidade </td>
                                <td> Bairro </td>
                                <td> Telefone </td>
                                <td> Options </td>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($customers as $customer)
                            <tr>
                                <td> {{$customer->id}}</td>
                                <td> {{$customer->fantasy_name}}</td>
                                <td> {{$customer->city}}</td>
                                <td> {{$customer->district}}</td>
                                <td> {{$customer->phone}}</td>
                                <td>
                                    {!! Form::open(['route' => ['customers.destroy', $customer->id], 'method' => 'DELETE'])!!}
                                        <a href="{{route('customers.edit', [$customer->id])}}" title="Edit"><i class="fa fa-pencil fa-fw"></i></a>
                                        <a href="{{route('customers.show', [$customer->id])}}" title="View"><i class="fa fa-eye fa-fw"></i></a>
                                        <button type="submit" title="Delete" class="btn-link"><i class="fa fa-trash-o fa-fw"></i></button>
                                    {!! Form::close()!!}

                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <div class="text-center">
                        {!! $customers->render()!!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/customers/view.blade.php
@extends('layouts.app')

@section('content')
    <div class="row well">
        <div class="col-lg-7">
            <h2>{{$customers->fantasy_name}}</h2>
            <p>Razão Social: {{$customers->company_name}}</p>
            <p>CNPJ: {{$customers->cnpj}}</p>
            <p>Email: {{$customers->email}}</p>
            <p>Telefone: {{$customers->phone}}</p>
            <p>Cidade: {{$customers->city}}</p>
            <p>Bairro: {{$customers->district}}</p>
            <p>Estado: {{$customers->state}}</p>
            <p>Endereço: {{$customers->address}}</p>
            <p>CEP: {{$customers->zip_code}}</p>
        </div>
    </div>
@stop