app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth'], function () {

    Route::get('/home', 'HomeController@index');

    Route::resource('/customers', 'CustomersController');

    Route::resource('/visits', 'VisitsController');

});
Route::auth();

app/Models/Visits.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Laracasts\Presenter\PresentableTrait;

class Visits extends Model
{

    use PresentableTrait;

    protected $presenter = \App\Presenters\VisitsPresenter::class;

    protected $table = 'visits';
    protected $fillable = [
        'customer_id',
        'visit_date',
        'sales_quantity',
        'value_received'
    ];

    // Implementar Pattern Presenter
    public function setValueReceivedAttribute($value)
    {
        $this->attributes['value_received'] = str_replace(',', '', $value);
    }

    public function customer()
    {
        return $this->belongsTo('App\Models\Customers');
    }
}

app/Http/Controllers/VisitsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\VisitsRequest;

use App\Models\Visits;

class VisitsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $visits = Visits::paginate(5);
        return view('visits.index', ['visits' => $visits]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('visits.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(VisitsRequest $request)
    {
        if (Visits::create($request->all())) {
            return redirect('/visits');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $visits = Visits::find($id);
        return view('visits.view', ['visits' => $visits]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $visits = Visits::find($id);
        return view('visits.edit', ['visits' => $visits]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(VisitsRequest $request, $id)
    {
        $visits = Visits::find($id);
        $visits->fill($request->all());
        $visits->save();

        return redirect('/visits');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Visits::destroy($id);
        return redirect('/visits');
    }
}

resources/views/visits/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h2>Nova Visita</h2>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-7">
                            {!!Form::open(['route'=>'visits.store', 'method'=>'POST'])!!}
                                @include('visits.form')
                                {!!Form::submit('Cadastrar', ['class' => "btn btn-lg btn-success"])!!}
                                <a href="{{ url()->previous() }}" class="btn btn-lg btn-danger">Back</a>
                            {!!Form::close()!!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/visits/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h2>Visita #{{$visits->id}}</h2>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-7">
                            {!!Form::model($visits, ['route'=> ['visits.update', $visits->id], 'method'=>'PUT'])!!}
                                @include('visits.form')
                                {!!Form::submit('Atualizar', ['class' => "btn btn-lg btn-success"])!!}
                                <a href="{{ url()->previous() }}" class="btn btn-lg btn-danger">Back</a>
                            {!!Form::close()!!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/visits/form.blade.php
<div class="form-group {{ $errors->has('customer_id') ? ' has-error' : '' }}">
    {!!Form::label('customer_id', 'Cliente', [])!!}
    {!!Form::select('customer_id', array('01' => 'Niterói', '02' => 'São Gonçalo'), null, ['placeholder' => 'Selecione o cliente...', 'class' => "form-control customers"])!!}
    @if ($errors->has('customer_id'))
        <span class="help-block">
            <strong>{{ $errors->first('customer_id') }}</strong>
        </span>
    @endif

</div>

<div class="form-group {{ $errors->has('visit_date') ? ' has-error' : '' }}">
    {!!Form::label('visit_date', 'Data da Visita', [])!!}
    <br>
    {!!Form::date('visit_date', \Carbon\Carbon::now())!!}
    @if ($errors->has('visit_date'))
        <span class="help-block">
            <strong>{{ $errors->first('visit_date') }}</strong>
        </span>
    @endif

</div>
<div class="form-group {{ $errors->has('sales_quantity') ? ' has-error' : '' }}">
    {!!Form::label('sales_quantity', 'Quantidade Vendida', [])!!}
    {!!Form::text('sales_quantity', null,['class' => "form-control", 'alt' => "Quantidade Vendida"])!!}
    @if ($errors->has('sales_quantity'))
        <span class="help-block">
            <strong>{{ $errors->first('sales_quantity') }}</strong>
        </span>
    @endif

</div>
<div class="form-group {{ $errors->has('value_received') ? ' has-error' : '' }}">
    {!!Form::label('value_received', 'Valor Recebido', [])!!} 
    <div class="input-group">
        <span class="input-group-addon">R$</span>
        {!!Form::text('value_received', null,['class' => "form-control value_received", 'alt' => "Valor Recebido"])!!}
    </div>
    @if ($errors->has('value_received'))
        <span class="help-block">
            <strong>{{ $errors->first('value_received') }}</strong>
        </span>
    @endif

</div>

<script type="text/javascript">
    $(document).ready(function() {
        $(".customers").select2();
        $('.value_received').mask("000.000.000.000.000,00", {reverse: true, 
            onComplete: function(cep) {
                alert('CEP Completed!:' + cep);
            }
        });
    });
</script>

resources/views/visits/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-success">
                <div class="panel-heading">Visitas</div>

                <div class="panel-body">
                    <a href="{{ url('/visits/create') }}" class="btn btn-success">Nova Visita</a>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <td> ID </td>
                                <td> Cliente </td>
                                <td> Data da Visita </td>
                                <td> Qtde. Vendida </td>
                                <td> Valor Recebido </td>
                                <td> Options </td>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($visits as $visit)
                            <tr>
                                <td> {{$visit->id}}</td>
                                <td> {{$visit->customer->fantasy_name}}</td>
                                <td> {{$visit->present()->visitDate}}</td>
                                <td> {{$visit->sales_quantity}}</td>
                                <td> {{$visit->present()->valueReceived}}</td>
                                <td>
                                    {!! Form::open(['route' => ['visits.destroy', $visit->id], 'method' => 'DELETE'])!!}
                                        <a href="{{route('visits.edit', [$visit->id])}}" title="Edit"><i class="fa fa-pencil fa-fw"></i></a>
                                        <a href="{{route('visits.show', [$visit->id])}}" title="View"><i class="fa fa-eye fa-fw"></i></a>
                                        <button type="submit" title="Delete" class="btn-link"><i class="fa fa-trash-o fa-fw"></i></button>
                                    {!! Form::close()!!}

                                </td>
                            </tr>
                        @endforeach  
                        </tbody>
                    </table>
                    <div class="text-center">
                        {!! $visits->render()!!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/visits/view.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h2>Visita</h2>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-7">
                            <h2>{{$visits->customer->fantasy_name}}</h2>
                            <p>Data : {{$visits->visit_date}}</p>
                            <p>Quantidade Vendida: {{$visits->sales_quantity}}</p>
                            <p>Valor Recebido: {{$visits->value_received}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop